# Generated by Django 2.0 on 2018-04-06 19:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=1000)),
                ('keywords', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data opublikowania')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_nick', models.CharField(blank=True, max_length=150, null=True)),
                ('comment', models.CharField(blank=True, max_length=600, null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonyme_confessions.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Reported_article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=500)),
                ('reported_article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonyme_confessions.Article')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonyme_confessions.User'),
        ),
    ]
