# Generated by Django 2.0 on 2018-04-07 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anonyme_confessions', '0004_auto_20180406_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 12, 6, 13, 876866, tzinfo=utc), verbose_name='Data opublikowania'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 12, 6, 13, 876866, tzinfo=utc), verbose_name='Data opublikowania'),
        ),
    ]
