# Generated by Django 2.0 on 2018-04-20 16:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anonyme_confessions', '0005_auto_20180407_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 16, 27, 22, 341268, tzinfo=utc), verbose_name='Data opublikowania'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 20, 16, 27, 22, 341268, tzinfo=utc), verbose_name='Data opublikowania'),
        ),
    ]
